import type { IndustryManifest } from "@/lib/industryManifests"

type ServiceItem = {
  name: string
  description: string
}

export type ContentGenerationInput = {
  name: string
  description: string
  industry: string
  subIndustry: string
  city: string | null
  state: string | null
  different: string
  services: ServiceItem[]
  vibe: string
  manifest: IndustryManifest
}

export type GeneratedWebsiteContent = {
  heroTitle: string
  heroSubtitle: string
  aboutText: string
  tagline: string | null
  ctaHeadline: string | null
  services: ServiceItem[]
}

type ClaudeMessageResponse = {
  content?: Array<{ type: string; text?: string }>
}

const ANTHROPIC_ENDPOINT = "https://api.anthropic.com/v1/messages"
const ANTHROPIC_VERSION = "2023-06-01"
const DEFAULT_MODEL = "claude-haiku-4-5"

function compact(value: string) {
  return value.replace(/\s+/g, " ").trim()
}

function limit(value: unknown, fallback: string, maxLength: number) {
  if (typeof value !== "string") return fallback
  const cleaned = compact(value)
  if (!cleaned) return fallback
  return cleaned.length > maxLength ? `${cleaned.slice(0, maxLength - 1).trim()}...` : cleaned
}

function serviceFallback(name: string) {
  return `Professional ${name.toLowerCase()} with clear communication, careful work, and a simple next step.`
}

function parseGeneratedJson(text: string): Record<string, unknown> | null {
  const trimmed = text.trim()
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/)
  const candidate = fenced?.[1]?.trim() || trimmed
  try {
    const parsed = JSON.parse(candidate)
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null
  } catch {
    return null
  }
}

function sanitizeServices(value: unknown, fallback: ServiceItem[]) {
  if (!Array.isArray(value)) return fallback

  const generated = value
    .map((item, index) => {
      if (!item || typeof item !== "object") return null
      const record = item as Record<string, unknown>
      const fallbackName = fallback[index]?.name || "Service"
      const name = limit(record.name, fallbackName, 60)
      return {
        name,
        description: limit(record.description, serviceFallback(name), 180),
      }
    })
    .filter(Boolean) as ServiceItem[]

  if (!generated.length) return fallback
  return fallback.map((service, index) => generated[index] || service)
}

export function buildFallbackWebsiteContent(input: ContentGenerationInput): GeneratedWebsiteContent {
  const cityLabel = input.city || "Your Area"
  const industryLabel = input.subIndustry.replace(/\b\w/g, (char) => char.toUpperCase())
  const locationPhrase = input.city
    ? `${input.city}${input.state ? `, ${input.state}` : ""}`
    : "Your Area"

  return {
    heroTitle: input.subIndustry ? `${industryLabel} in ${cityLabel}` : input.name,
    heroSubtitle: input.manifest.primaryJob,
    aboutText: `${input.name} is a locally owned ${industryLabel.toLowerCase()} business serving ${locationPhrase}. ${input.manifest.primaryJob}`,
    tagline: null,
    ctaHeadline: null,
    services: input.services.length
      ? input.services
      : [{
          name: industryLabel || "Service",
          description: serviceFallback(industryLabel || "service"),
        }],
  }
}

function buildPrompt(input: ContentGenerationInput) {
  return [
    "Create concise homepage copy for a small business website generated by Found Co.",
    "Write like Apple would for a local business: clear, human, premium, and simple. No hype. No jargon. No emojis.",
    "Return JSON only with this exact shape:",
    '{"heroTitle":"string","heroSubtitle":"string","aboutText":"string","tagline":"string or null","ctaHeadline":"string or null","services":[{"name":"string","description":"string"}]}',
    "",
    `Business name: ${input.name}`,
    `What they do: ${input.description || "Not provided"}`,
    `Industry: ${input.industry}`,
    `Sub-industry: ${input.subIndustry}`,
    `Location: ${[input.city, input.state].filter(Boolean).join(", ") || "Not provided"}`,
    `What makes them different: ${input.different || "Not provided"}`,
    `Selected vibe: ${input.vibe}`,
    `Primary customer job: ${input.manifest.primaryJob}`,
    `Jony design note: ${input.manifest.jonyNote}`,
    `Primary call to action intent: ${input.manifest.primaryIntent}`,
    `Secondary call to action intent: ${input.manifest.secondaryIntent || "none"}`,
    `Services to keep in this order: ${input.services.map((service) => service.name).join(", ") || "Create one general service"}`,
    "",
    "Rules:",
    "- Keep heroTitle under 64 characters.",
    "- Keep heroSubtitle under 150 characters.",
    "- Keep aboutText under 420 characters.",
    "- Keep each service description under 160 characters.",
    "- Preserve the provided service names unless they are unclear; lightly clean them only.",
    "- Do not invent license numbers, awards, prices, guarantees, credentials, or years in business.",
  ].join("\n")
}

export async function generateWebsiteContent(input: ContentGenerationInput): Promise<GeneratedWebsiteContent> {
  const fallback = buildFallbackWebsiteContent(input)
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) return fallback

  try {
    const response = await fetch(ANTHROPIC_ENDPOINT, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": ANTHROPIC_VERSION,
      },
      body: JSON.stringify({
        model: process.env.ANTHROPIC_MODEL || DEFAULT_MODEL,
        max_tokens: 900,
        temperature: 0.4,
        messages: [{ role: "user", content: buildPrompt(input) }],
      }),
    })

    if (!response.ok) {
      console.error("[contentGeneration] Claude request failed:", response.status, await response.text())
      return fallback
    }

    const payload = await response.json() as ClaudeMessageResponse
    const text = payload.content?.find((block) => block.type === "text")?.text
    const generated = text ? parseGeneratedJson(text) : null
    if (!generated) return fallback

    return {
      heroTitle: limit(generated.heroTitle, fallback.heroTitle, 64),
      heroSubtitle: limit(generated.heroSubtitle, fallback.heroSubtitle, 150),
      aboutText: limit(generated.aboutText, fallback.aboutText, 420),
      tagline: typeof generated.tagline === "string" ? limit(generated.tagline, "", 80) || null : null,
      ctaHeadline: typeof generated.ctaHeadline === "string" ? limit(generated.ctaHeadline, "", 90) || null : null,
      services: sanitizeServices(generated.services, fallback.services),
    }
  } catch (error) {
    console.error("[contentGeneration] Claude generation error:", error)
    return fallback
  }
}
