/**
 * Backfill script: generates copy (heroTitle, heroSubtitle, aboutText, tagline,
 * ctaHeadline, faq_items) for companies that are missing it.
 *
 * Usage:
 *   node scripts/backfill-copy.mjs
 *
 * Requires environment variables from .env.local (load manually or use dotenv).
 * The script reads .env.local automatically.
 */

import { readFileSync } from "fs"
import { createClient } from "@supabase/supabase-js"

// ── Load .env.local ────────────────────────────────────────────────────────────
function loadEnv() {
  try {
    const raw = readFileSync(new URL("../.env.local", import.meta.url), "utf8")
    for (const line of raw.split("\n")) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith("#")) continue
      const eq = trimmed.indexOf("=")
      if (eq === -1) continue
      const key = trimmed.slice(0, eq).trim()
      const val = trimmed.slice(eq + 1).trim()
      if (!process.env[key]) process.env[key] = val
    }
  } catch {
    // .env.local not found — rely on existing process.env
  }
}
loadEnv()

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY
const ANTHROPIC_ENDPOINT = "https://api.anthropic.com/v1/messages"
const ANTHROPIC_VERSION = "2023-06-01"
const MODEL = process.env.ANTHROPIC_MODEL || "claude-haiku-4-5"

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY")
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

// ── Helpers ────────────────────────────────────────────────────────────────────

function compact(value) {
  return value.replace(/\s+/g, " ").trim()
}

function limit(value, fallback, maxLength) {
  if (typeof value !== "string") return fallback
  const cleaned = compact(value)
  if (!cleaned) return fallback
  return cleaned.length > maxLength ? `${cleaned.slice(0, maxLength - 1).trim()}...` : cleaned
}

function parseGeneratedJson(text) {
  const trimmed = text.trim()
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/)
  const candidate = fenced?.[1]?.trim() || trimmed
  try {
    const parsed = JSON.parse(candidate)
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : null
  } catch {
    return null
  }
}

function sanitizeFaqItems(value) {
  if (!Array.isArray(value)) return null
  const items = value
    .slice(0, 3)
    .map((item) => {
      if (!item || typeof item !== "object") return null
      const q = typeof item.q === "string" ? compact(item.q).slice(0, 160) : null
      const a = typeof item.a === "string" ? compact(item.a).slice(0, 300) : null
      if (!q || !a) return null
      return { q, a }
    })
    .filter(Boolean)
  return items.length > 0 ? items : null
}

function buildPrompt(company, config) {
  const name = company.name
  const industry = company.industry_category
  const subIndustry = company.sub_industry || industry
  const city = company.city || null
  const state = company.state || null
  const location = [city, state].filter(Boolean).join(", ") || "Not provided"
  const services = (config?.services || []).map(s => s.name).join(", ") || "Create one general service"

  return [
    "Create concise homepage copy for a small business website generated by Found Co.",
    "Write like Apple would for a local business: clear, human, premium, and simple. No hype. No jargon. No emojis.",
    "Return JSON only with this exact shape:",
    '{"heroTitle":"string","heroSubtitle":"string","aboutText":"string","tagline":"string or null","ctaHeadline":"string or null","services":[{"name":"string","description":"string"}],"faqItems":[{"q":"string","a":"string"},{"q":"string","a":"string"},{"q":"string","a":"string"}]}',
    "",
    `Business name: ${name}`,
    `Industry: ${industry}`,
    `Sub-industry: ${subIndustry}`,
    `Location: ${location}`,
    `Services to keep in this order: ${services}`,
    "",
    "Rules:",
    "- Keep heroTitle under 64 characters.",
    "- Keep heroSubtitle under 150 characters.",
    "- Keep aboutText under 420 characters.",
    "- Keep each service description under 160 characters.",
    "- Preserve the provided service names unless they are unclear; lightly clean them only.",
    "- Do not invent license numbers, awards, prices, guarantees, credentials, or years in business.",
    "- Generate exactly 3 FAQ entries in faqItems. Questions and answers should sound like a real owner wrote them, specific to this business type and location.",
    "- FAQ answers must include the business name and city naturally, and should be 1-2 sentences max.",
    "- Questions should be what real customers actually search: service-specific, location-aware, and conversational.",
  ].join("\n")
}

async function generateForCompany(company, config) {
  if (!ANTHROPIC_API_KEY) {
    console.warn(`  [skip] No ANTHROPIC_API_KEY — cannot generate for ${company.name}`)
    return null
  }

  const prompt = buildPrompt(company, config)
  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 12000)
    const response = await fetch(ANTHROPIC_ENDPOINT, {
      method: "POST",
      signal: controller.signal,
      headers: {
        "content-type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": ANTHROPIC_VERSION,
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 1200,
        temperature: 0.4,
        messages: [{ role: "user", content: prompt }],
      }),
    })
    clearTimeout(timeout)

    if (!response.ok) {
      console.error(`  [error] Claude request failed for ${company.name}: ${response.status}`)
      return null
    }

    const payload = await response.json()
    const text = payload.content?.find(b => b.type === "text")?.text
    const generated = text ? parseGeneratedJson(text) : null
    if (!generated) {
      console.warn(`  [warn] Could not parse Claude response for ${company.name}`)
      return null
    }

    const fallbackHero = `${company.name}${company.city ? ` — ${company.city}` : ""}`
    return {
      hero_title: limit(generated.heroTitle, fallbackHero, 64),
      hero_subtitle: typeof generated.heroSubtitle === "string" ? limit(generated.heroSubtitle, "", 150) || null : null,
      about_text: typeof generated.aboutText === "string" ? limit(generated.aboutText, "", 420) || null : null,
      tagline: typeof generated.tagline === "string" ? limit(generated.tagline, "", 80) || null : null,
      cta_headline: typeof generated.ctaHeadline === "string" ? limit(generated.ctaHeadline, "", 90) || null : null,
      faq_items: sanitizeFaqItems(generated.faqItems),
      copy_generated: true,
    }
  } catch (err) {
    console.error(`  [error] Generation failed for ${company.name}:`, err.message)
    return null
  }
}

// ── Main ───────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Fetching companies needing copy backfill...")

  // Fetch companies where website_config.copy_generated is false OR faq_items IS NULL
  const { data: companies, error } = await supabase
    .from("companies")
    .select("id, name, industry_category, sub_industry, city, state, website_config(id, copy_generated, faq_items, services, hero_title, hero_subtitle, about_text, tagline, cta_headline)")
    .or("website_config.copy_generated.is.false,website_config.faq_items.is.null,website_config.is.null")
    .order("created_at", { ascending: false })

  if (error) {
    console.error("Failed to fetch companies:", error.message)
    process.exit(1)
  }

  // Filter to companies where copy_generated is false OR faq_items is null
  const targets = (companies || []).filter(c => {
    const wc = Array.isArray(c.website_config) ? c.website_config[0] : c.website_config
    if (!wc) return true
    return !wc.copy_generated || wc.faq_items === null || wc.faq_items === undefined
  })

  console.log(`Found ${targets.length} companies to backfill.`)
  if (targets.length === 0) {
    console.log("Nothing to do.")
    return
  }

  let success = 0
  let failed = 0

  for (let i = 0; i < targets.length; i++) {
    const company = targets[i]
    const wc = Array.isArray(company.website_config) ? company.website_config[0] : company.website_config
    console.log(`[${i + 1}/${targets.length}] ${company.name} (${company.id})`)

    const generated = await generateForCompany(company, wc)
    if (!generated) {
      failed++
      continue
    }

    // Build upsert payload — only overwrite empty fields if they already have values
    const upsertPayload = {
      company_id: company.id,
      faq_items: generated.faq_items,
      copy_generated: true,
    }
    // Only set content fields if they were empty before
    if (!wc?.hero_title) upsertPayload.hero_title = generated.hero_title
    if (!wc?.hero_subtitle) upsertPayload.hero_subtitle = generated.hero_subtitle
    if (!wc?.about_text) upsertPayload.about_text = generated.about_text
    if (!wc?.tagline) upsertPayload.tagline = generated.tagline
    if (!wc?.cta_headline) upsertPayload.cta_headline = generated.cta_headline

    const { error: upsertError } = await supabase
      .from("website_config")
      .upsert(upsertPayload, { onConflict: "company_id" })

    if (upsertError) {
      console.error(`  [error] Failed to upsert for ${company.name}:`, upsertError.message)
      failed++
    } else {
      console.log(`  [ok] Generated copy + ${generated.faq_items ? generated.faq_items.length : 0} FAQs`)
      success++
    }

    // Small delay to avoid API rate limits
    if (i < targets.length - 1) {
      await new Promise(r => setTimeout(r, 300))
    }
  }

  console.log(`\nDone. Success: ${success} | Failed: ${failed}`)
}

main().catch(err => {
  console.error("Backfill script error:", err)
  process.exit(1)
})
